site_name: {{mkdocs_title}}

docs_dir: '{{mkdocs_dir}}/mkdocs_pages'
site_dir: '{{mkdocs_dir}}/static/mkdocs_build'

pages:
  {% for page, md in mkdocs_pages.items %}
  - {{page}}: {{md}}
  {% endfor %}
